version: "3.7"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-new-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: anu
      MYSQL_PASSWORD: Anu@1234567890
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: docker
    ports:
      - "3306:3306"
    volumes:
      - db-student-data:/var/lib/mysql
    networks:
      - my-new-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

networks:
  my-new-network:
    driver: bridge

volumes:
  db-student-data: